# Generated by Django 4.1 on 2022-08-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
